
export const data1 = {
    psychology: [
        " Posting a calorie chart in fast food restaurants leads people to choose less healthy foods.",
        " Expectant fathers can sometimes experience a sympathetic pregnancy where they have symptoms like back ache, weight gain, strange food cravings and nausea. This has also been found to happen in some species of monkey.",
        " As many as 9% of adult Americans have been to an alcoholics anonymous meeting at some time in their life (Moos & Timko, 2008).",
        " 1 in 5 women and 1 in 20 men admit to sleeping with a cuddly toy on a regular basis (Kanner, 1995).",
        " Suicidal thinking or behaviour is the most common reason for people to be admitted into a mental institution (Jacobson, 1999).",
        " Women who live in\u00a0warmer climates\u00a0have more body image concerns than those who live in colder climates (Sloan, 2002).",
        " The U.S has the highest rate of rape for any industrialized nation. 4 times higher than Germany, 12 times higher than England and 20 times higher than Japan (Rozee, 2005).",
        " People with generally high levels of anxiety are more likely to remember pictures of threatening faces than calmer people (bradley et al, 1998).",
        " Fear of injection",
        " On average it takes 66 days to form a habit.",
        " On average your mind wanders 30% of the time.",
        " We think that other people are more easily influenced than ourselves.",
        " 1 in 12 people have sex in their sleep.",
        " The most common\u00a0lie\u00a0is \u2018I\u2019m fine\u2019",
        " The average person tells 4 lies a day, 1460 a year and a total of 87,600 by the time they\u2019re 60.",
        " People who spend more time in the sun are likely to be happier and happy people are more likely to fall in love because their happiness is infectious.",
        " If someone makes eye contact with you for 60% of a conversation they\u2019re bored, 80% and they\u2019re attracted to you and 100% of the time then they are threatening you.",
        " The pupil of your eye expands up to 45% when you look at someone you love.",
        " It takes 4 seconds for a silence to become awkward.",
        " When you\u2019re hurt cursing helps to reduce pain.",
        " We can udnretsnad any msseed up stnecene as lnog as the lsat and frsit lteerts of wdros are in crrcoet palecs",
        " Its easier to remember things with your eyes closed.",
        " Unhappy people watch more TV.",
        " Having siblings is proven to help socialization with peers.",
        " What we wear affects how we behave.",
        " When crying from happiness the first tear will come from the right eye but if you are crying from sadness it will come from the left.",
        " Most people text faster when its someone they like.",
        " When flirting the average amount of glances to 'send a signal 2019' is 3.",
        " Usually thinking of a successful outcome will reduce our motivation rather than increase it.",
        " In Milgrams obedience study 63% of participants kept giving seemingly lethal electric shocks because an authority figure was telling them to.",
        " The word psychology comes from the Greek word psyche meaning \u2018breath, spirit, soul\u2019 and the logia meaning 2018 study of 2019",
        " Negative reinforcement works better than punishment as a disciplinary measure.",
        " Smiling can make you feel happier.",
        " Cats have almost twice as many neurons in their brain as dogs.",
        " Alcohol is involved in 90% of cases of sexual assault on college campuses.",
        " Almost half of all married couples 75 and older still have sex on a regular basis.",
        " Over half of the U.S population believe in psychic phenomena.",
        " Placebos can be as good as real treatments.",
        " Freud initially only sold 700 copies of the interpretation of dreams.",
        " Studies have shown that eating food without preservatives can improve I.Q by up to 14%.",
        " Excessive stress can alter brain cells, structure and function.",
        " Smiling is 69% more attractive than wearing makeup (Orbit complete healthy smile campaign, 2009)",
        " The brain is made up of 75% water.",
        " Akira Haraguchi recited 100,000 digits of pi in 16 hours.",
        " The world record time without sleep is 264 hours.",
        " Our brain size has fallen 10% in mass since we were hunter gatherers.",
        " The human brain weighs 1300-1400g which is proportionately more for body size than any other species.",
        " Working memory can hold 7+/- 2 pieces of information.",
        " People are often more productive in blue rooms",
        " Your sense of smell is the sense which is best attached to your memory.",
        " A small amount of stress helps you to remember things better but a large amount hinders your memory.",
        " Men say approximately 12,500 words per day whereas women say 22,000.",
        " The pursuit of food and water is the most powerful motivator. (Doddard & Miller, 1950)",
        " Some of the cells in your visual cortex only respond to horizontal information and others only respond to vertical stimuli (Hubel & Weisel, 1959)",
        " 9% of men and 0.5% of women are colour blind.",
        " In 1909, a scientist by the name of Thomas H. Morgan discovered that chromosomes contained inherited information.",
        " Female serial killers account for only 8% of all American serial killers, but American females account for 76% of all female serial killers worldwide.",
        " We are most creative at night and least creative in the afternoons.",
        " People are more likely to return a lost wallet if there is a baby picture found inside of it.",
        " The colour blue causes the brain to release relaxing hormones.",
        " The only innate emotions are joy, acceptance, fear, surprise, sadness, disgust, anger, and anticipation. Other more complicated emotions like love and guilt are believed to be combinations of these. (Plutchik, 1980)",
        " People are more likely to blame other people rather than the situation when something bad happens.",
        " There are 5 key aspects to personality: extraversion, agreeableness, conscientiousness, neuroticism and openess.",
        " Sex is not distributed equally, over 50% of sexual activity in the US is performed by only 15% of the population (General social survey, 1998).",
        " Retro grade amnesia is a condition where you don\u2019t remember anything before your trauma.",
        " Cognitive dissonance is when you have two conflicting beliefs and you adjust one to fit the other.",
        " People read faster with longer lines but prefer shorter ones.",
        " Most people imagine things from above and at an angle.",
        " Chromostereopsis is when two colours are together and one of them sticks out more than the other. This effect is most obvious with the colours red and blue.",
        " Larger groups make poorer and more emotional decisions than small groups or individuals.",
        " Studies reveal that people recognize and interpret the emotional facial expressions of those in their own race faster than those who are a different race. (MacDonald & Matthew, 2008)",
        " Repetition physically changes your brain as new connections are made between brain cells.",
        " The human attention span maxes out at about 10 minutes, over that and we will tend to revert to daydreaming.",
        " The maximum number of close relationships/friendships you can maintain is between 50 and 150.",
        " Girl talk helps women to form closer bonds but also increases depression and anxiety.",
        " Anti-social or unpopular teenage girls are 70% more likely to put on weight than popular, sociable girls (Lemeshow, 2008)",
        " A study at John Hopkins University found that the myth that you yawn for your brain to get more oxygen is untrue. It is in fact to cool your brain down",
        "Junk food diets for kids under three can lead to lower IQs",
        "Summer vacation can drop your IQ",
        "For each one-point increase in a country’s average IQ, the per capita GDP was $229 higher, and can go up to $468 higher for each additional point",


    ],
  
    "phobias": [" Phobophobia-Fear of phobias",
                " Soceraphobia-Fear of parents in law",
                " Pogonophobia-Fear of beards",
                " Triskidekaphobia-Fear of the number 13",
                " Olfactophobia-Fear of smells",
                " Mnemophobia-Fear of memories",
                " Laliophobias-Fear of speaking",
                " Latrophobia-Fear of doctors or going to the doctors",
                " Geliophobia-Fear of laughter",
                " Chronophobia-Fear of time",
                " Catoptrophobia-Fear of mirrors",
                " Allodoxophobia-Fear of opinions",
                " Amaxophobia-Fear of riding in a car",
                " Androphobia-Fear of men",
                "Barophobia-Fear of gravity",
                "Cyberphobia-Fear of computers",
                "Cynophobia-Fear of dogs",
                "Mephobia-Fear of becoming so awesome that the human race can't handle it",
                "Necrophobia-Fear of death or dead things",
                "Obesophobia-Fear of gaining weight",
                "Pyrophobia-Fear of fire",
                "Xenophobia-Fear of strangers or foreigners",
                "Sociophobia: Fear of social evaluation",
                "Scoptophobia: Fear of being stared at"
            ],
  
    "introverts": ["Introversion is one of the major personality traits identified in many theories of personality.Introverts tend to be more quiet, reserved, and introspective",
                   "Introverts are Curious independent and highly self motivated. Prefers to work alone.",
                   "People who are introvert tend to be inward turning, or focused more on internal thoughts, feelings and moods rather than seeking out external stimulation.",
                   "Introverts need some time to do self introspection and do things they enjoy.Introverts enjoy solitude most of the time.",
                   "Introverts Can be lazy and procrastinating but once they set their mind on something .will give their best.",
                   "Introvert always prefers one-to-one chat to person instead of group conversations.",
                   "Introverts are best in Creative,Marketing and Educational Field.Some of the Introverts are:Bill Gates,Steven Spielberg,Emma Watson,Steve Jobs,JK Rowlings,Albert Einstein,Issac Newton,Mark Zukerburg,Warren Buffet,Elon Musk,Larry Page,Barack Obama.",
                   "Introverts Prefer quality over quantity.They have very few friends ,whom they can trust or no friends at all. They don’t prefer superficial relationships,better to have no friends than have superficial friends.",
                   "Introverts Hate small talk. don’t initiate conversations .don’t speak unless they want to .prefers intellectual conversations.but once you get them talking. they can be hard to stop.",
                   "Introverts are Highly sensitive ,empathetic .avoids conflicts most of the time.hence can be misunderstood as weak and subservient.",
                   "Introverts have a best creativity knowledge So they can be good artists ,writers ,musicians etc.",
                   "Most Introverts hates phone calls as they lead to unnecessary conversation. Hence prefers to text as they are good at writing.",
                   "Introverts are Highly caring and altruistic not that interested in material comforts .wants to make the world a better place.but often misunderstood as arrogant or weird.",
                   "Introverts Loves nature,music ,books,movies documentaries ,pets etc",
                   "Introverts are most likely to be depressed easily but can bounce back stronger.",
                   "Introverts hates parties and other social gatherings too many people .too much bickering which drains their energy.",
                   "Introverts don’t like to draw attention to themselves.",
                   "One biological theory explains that introverts naturally have high cortical arousal (the speed and amount of brain activity) and may process more information per second. Therefore, introverts tend to avoid highly active environments.",
                   "If you place introverts in a busy environment, their brain will quickly overload and shut down to stop the inflow of information. This is why introverts wind down at the end of the day – to recharge that lost energy.",
                   "Introverts ideal eating setups are at home with some soulful music around rather than big restaurants.",
                   "Introverts have Thicker Nerve Tissues in the Prefrontal Cortex (Part of the brain responsible for making decisions). Hence, It’s speculated that introverts tend to make better decisions, while extroverts are able to live in the moment without thinking or worrying too much.",
                   "Introverts do not tend to have tons of friends.Instead, they intensely value their close friends. If you have an introvert friend, you probably have an ally for life.",
                   "Introverts want company just as much as extroverts do, but they prefer it in either short closes or with people they know well.",
                   "Introverts are reserved, plan their actions and control their emotions. They tend to be serious,reliable and pessimistic.",
                   "Introverts tend to be preoccupied with their own thoughts and feelings and minimize their contact with other people.",
                   "Rainy days at home are blessings Period for Introverts according to surveys.",
                   "Being an introvert has nothing to do with shyness, nor does it imply that they are afraid of interacting with others. What it does mean is that introverts often do not interact simply for the sake of interacting.",
                   "Recharging is important to introverted individuals. Rather that going out all of the time, they place a high value on quiet and restful time so that they can feel refreshed and prepared.",
                   "Those who are introverted do not necessarily want to be alone all the time. However, they do tend to be more comfortable with their own thoughts than others.",
                   "Introverts generally prefer to be valued for what they can bring to the table as an individual rather than how well they fit in with a group. Because they prefer to think for themselves, they seldom are left to follow what is thought of as popular.",
                   "Introverts cannot be expected to “become” extroverts. They simply have a different temperament and manner of handling things. Sometimes the best solutions come from having a combination of the two personality types."

    ],

    "extroverts": ["Extroverts are Happier People.Extroverts place their feelings out in the open and have little fear of judgment. They thus tend to be happier people and their many friends are good resources too.",
                    "Extrovert boys are very friendly. They are also very talkative and like to make new friends and like social gatherings.",
                    "Psychological Facts of Extroverts says Girls are attracted much towards Extrovert types of guys. Extrovert guys are full of confident and adventurers.",
                    "Extroverts are Enjoys being at the center of attention or leader of the team.",
                    "Extroverts Feels isolated by too much time spent alone.they prefered and enjoys the group work.",
                    "At a party, an extrovert will probably be the first one to walk up to new guests and make introductions. It is for this reason that extroverts typically find it easy to meet new people and make new friends.",
                    "Extroverts are typically very open and willing to share their thoughts and feelings. Because of this, other people generally find that extroverts are easier to get to know.",
                    "Extroverts are also more likely to engage in risk-taking behaviors, including risky health behaviors.",
                    "Although being loud and bubbly is thought to be a common trait of extroverts, not all extroverts fit into this mold. Being extroverted is not about whether or not an individual is loud or talkative.",
                    "Extroverts, although many are certainly good at public speaking, are not naturally skilled speakers. An extrovert could just as easily share a fear of public speaking as an introvert.",
                    "Although extroverts get much of their energy from the presence of others, they still need time to be alone and gather their thoughts.",
                    "Extroverts can be great listeners even though they are thought to be overly talkative. They also tend to be very understanding and likely to know a comforting this to say.",
                    "There is no data that says extroverts are happier than introverts. They are simply two different personality types and function in two differing ways.But Extroverts are more carefree than introverts.",
                    "Extroverted individuals are often more “touchy-feely” than their introverted counterparts. While an extrovert might go for a hug when seeing a friend, an introvert is less likely to initiate such contact.",
                    "Extroverts sometimes come across as seeming “phony.” However, they do not purposefully put on a phony persona, they usually just wish to adapt to their surroundings.",
                    "Psychological Facts of Extroverts says They are highly likely to compromise their own happiness or comfort to make someone that they care about happy.",
                    "Extroverts often enjoy the company of many people but that does not mean that they don’t enjoy having close friends or spending time with only a few close people.",
                    "Extroverts love traveling and loves to explore new places and experience.",
                    "The extrovert is characteristically the active person who is most content when surrounded by people; carried to the neurotic extreme such behavior appears to constitute an irrational flight into society, where the extrovert’s feelings are acted out.",
                    "Extroverts need to talk their problems through, asking others to help them look at all angles of a situation.",
                    "Extroverts are expected to be the one to keep up the conversation or feel instantly comfortable when confronting a stranger.But some extroverts can still have the “I am shy until you get to know me” personality.",
                    "Despite the fact that extroverts are talkative, they really do like to listen! They want to hear about what is going on in the life of people around them.",
                    "Extroverts are good presentators ,they can present any things in a positive way or a negative way also.",
                    "Extroverts likes when someone ask them for advice.They are very happy to be the adviser.",
                    "Extroverts don’t understand their introvert friends at all.Most of time they tries to make introverts like them.",
                    "Extroverts are always like to do some tasks,instead of sitting ideal.",
                    "Study of Psychological Facts of Extroverts says Extroverts are somehow less intelligent than introverts.But they are more experienced than introverts.",
                    "Extroverts can easily move on through difficult situation in comparision of introverts they can forget their past very fast.",
                    "Study suggested that the variability in this trait might be linked to differences in cortical arousal. Extroverts tend to need more external stimulation while introverts tend to become stimulated very easily.",
                    "Psychological Facts of Extroverts study says Extrovert guys feel less awkward in new conditions and they are fast to grasp transformation in their life.",
                    "Extroverts are often unfairly pegged as overly-talkative or attention-seeking. In reality, they simply gain energy from engaging in social interaction",
                    "People who are high in extroversion need social stimulation to feel energized. They gain inspiration and excitement from talking and discussing ideas with other people.",
                    "Extroversion clearly has a strong genetic component. Twin studies suggest that genetics contribute somewhere between 40 and 60 percent of the variance between extroversion and introversion."
        
    ]

  };
